#! /bin/sh
dll_find="./tools/dll_find"
exe_name="cstarter"
exe_suffix=".exe"
bin_folder="./bin/Release/"
bin_file=${bin_folder}${exe_name}${exe_suffix}
deploy_folder="./bin/Deploy/Windows_x64"

mkdir -p $deploy_folder
cp $bin_file $deploy_folder
cp $($dll_find $bin_file) $deploy_folder

#testa=$(dirname $0)
#echo $testa