#! /bin/sh
so_find="./tools/so_find"
exe_name="cstarter"
exe_suffix=""
bin_folder="./bin/Release/"
bin_file=${bin_folder}${exe_name}${exe_suffix}
deploy_folder="./bin/Deploy/Linux_x64"

chmod +x $bin_file
mkdir -p $deploy_folder
cp $bin_file $deploy_folder
cp $($so_find $bin_file) $deploy_folder

#testa=$(dirname $0)
#echo $testa